name: "Static analysis"

on:
  push:
    branches:
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
  pull_request:

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "PHP-CS-Fixer"
        uses: "docker://oskarstark/php-cs-fixer-ga:2.19.0"
        with:
          args: --diff --dry-run
